examples/smbexec.py: Use %COMPUTERNAME% in UNC path
Using the RFC1060 localhost IP doesn't resolve successfully on
all machines:

	C:\>echo foo > \\127.0.0.1\C$\bar
	echo foo > \\127.0.0.1\C$\bar
	The specified user does not exist.

	C:\>echo foo > \\localhost\C$\bam
	echo foo > \\localhost\C$\bam
	You were not connected because a duplicate name exists on the network. Go to System in Control Panel to change the computer name and try again.

	C:\>echo fo > \\localhost.localdomain\C$\bam
	echo fo > \\localhost.localdomain\C$\bam

	The network path was not found.

However, UNC paths work well and are documented to use the computer's
name for addressing.  Hence, switch to %COMPUTERNAME% for more reliable
execution.

Otherwise we may have errors such as:

	impacket.dcerpc.v5.scmr.DCERPCSessionError: SCMR SessionError: code: 0x41d - ERROR_SERVICE_REQUEST_TIMEOUT - The service did not respond to the start or control request in a timely fashion.
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/impacket/smbconnection.py", line 769, in getFile
	    return self._SMBConnection.retr_file(shareName, pathName, callback)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib/python3/dist-packages/impacket/smb.py", line 4009, in retr_file
	    fid = self.nt_create_andx(tid, filename, shareAccessMode = shareAccessMode, accessMask = 0x20089)
	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/jkoenig/MS17-010/examples/smbexec.py", line 206, in nt_create_andx
	    self._last_fid = smb.SMB.nt_create_andx(self, tid, filename, smb_packet, cmd, shareAccessMode, disposition, accessMask)
	                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib/python3/dist-packages/impacket/smb.py", line 3896, in nt_create_andx
	    if smb.isValidAnswer(SMB.SMB_COM_NT_CREATE_ANDX):
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib/python3/dist-packages/impacket/smb.py", line 778, in isValidAnswer
	    raise SessionError("SMB Library Error", self['ErrorClass'] + (self['_reserved'] << 8), self['ErrorCode'], self['Flags2'] & SMB.FLAGS2_NT_STATUS, self)
	impacket.smb.SessionError: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

	CRITICAL:root:SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)