Fix SMB relay server not gracefully replying to SMB packets (#2114)
If an SMB packet is incoming and wants to negotiate and smb2support is
enabled, before this would throw an exception while trying to parse the
SMB packet as an SMB2 packet:
```
Traceback (most recent call last):
  File
"/Users/roman/.local/pipx/venvs/impacket/lib/python3.13/site-packages/impacket/smbserver.py",
line 4191, in handle
    resp = self.__SMB.processRequest(self.__connId, p.get_trailer())
  File
"/Users/roman/.local/pipx/venvs/impacket/lib/python3.13/site-packages/impacket/smbserver.py",
line 4865, in processRequest
    respPacket['CreditRequestResponse'] =
packet['CreditRequestResponse']

~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/Users/roman/.local/pipx/venvs/impacket/lib/python3.13/site-packages/impacket/structure.py",
line 186, in __getitem__
    return self.fields[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'CreditRequestResponse'
```
By sending the SMB2 packet response directly instead of the command,
this should now work properly.